version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}/db_dumps/database_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - likeavito_docker_network

  redis:
    image: redis:5.0
    restart: always
    networks:
      - likeavito_docker_network
  
  rabbitmq:
    image: rabbitmq:3.9
    restart: always
    networks:
      - likeavito_docker_network

  server:
    depends_on:
      - db
      - redis
      - rabbitmq
    build: .
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ${PWD}/conf/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${PWD}/conf/hosts:/etc/hosts
    networks:
      - likeavito_docker_network
networks:
  likeavito_docker_network: